Improve tests
phpDocumentor/FlyFinder pull request #4
Opened 2017-12-11 00:30 UTC by carusogabriel

I've improved our tests, using the `PHPUnit\Framework\TestCase` notation and `assertCount` in some assertions.

2018-01-08 11:35 UTC, ashnazg commented
Ah, wish I had looked at this one and merged it before my previous one.  I had to do the `TestCase` change to get my bump-to-7.1 to work.

@carusogabriel, can you redo this with just the `assertCount` changes?

2018-01-08 11:37 UTC, ashnazg requested changes
Only include assertCount changes, as Test case and PHPUnit changes were already done separately.

2018-01-09 01:56 UTC, carusogabriel commented
Done. Also used `assertSame` (===) instead of `assertEquals` (==) :+1:

2018-01-09 02:09 UTC, ashnazg approved these changes

2018-01-09 14:32 UTC, merged